name: pytest
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: 3.10.0
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv codecov
        pip install -r requirements.txt
        pipenv install --dev
    - name: Test with pytest
      run: |
        pytest -vv --cov resources/home/dnanexus/dias_batch/
